version: "3"

services:
  zeebe:
    image: ghcr.io/camunda-community-hub/zeebe-with-hazelcast-exporter:latest
    container_name: zeebe
    environment:
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
    ports:
      - 26500:26500
      - 5701:5701
    volumes:
      - zeebe:/usr/local/zeebe/data
      - ./lib/zeebe-hazelcast-exporter-1.1.0-jar-with-dependencies.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network
    depends_on:
      - elasticsearch

  operate:
    image: camunda/operate:${CAMUNDA_CLOUD_VERSION:-1.3.5}
    container_name: operate
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 8080:8080
    networks:
      - zeebe_network
    depends_on:
      - elasticsearch

  tasklist:
    image: camunda/tasklist:${CAMUNDA_CLOUD_VERSION:-1.3.5}
    container_name: tasklist
    environment:
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 8081:8080
    networks:
      - zeebe_network
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.16.1}
    container_name: elasticsearch
    environment:
      - cluster.name=camunda-cloud
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - zeebe_network

  monitor:
    container_name: zeebe_monitor
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.3.0
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    # volumes:
    #   - ./simple-monitor-application.yaml:/usr/local/zeebe/config/application.yaml
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network

  golang:
    container_name: golang
    image: golang
    command: bash -c "while true; do echo hello; sleep 2; done"
    working_dir: /home/apps
    depends_on:
      - zeebe
    volumes:
      - .:/home/apps
    environment:
      ZEEBE_ADDRESS: zeebe_broker
      ZEEBE_CLIENT_ID: wallet_svc
      ZEEBE_CLIENT_SECRET:
      ZEEBE_AUTHORIZATION_SERVER_URL:
    networks:
      - zeebe_network

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - zeebe_network
    restart: unless-stopped

volumes:
  postgres:
  elastic:
    driver: local
  zeebe:
    driver: local

networks:
  zeebe_network:
    driver: bridge
